### ISSUE TITLE
How to setup the project?

### ISSUE THREAD

**Issue by chahna107** [loomchild/maligna#2]
Hi @loomchild,
Could you please provide detailed steps on how to use your project? I downloaded the jar file from Maven Central. However, based on the commands in the readme I am unable to follow how to setup the project and run the commands.
Your help will be appreciated.

Thank you!

**Comment by loomchild** [comment]
Hi Chahna,

Could you clarify what are you trying to do and where exactly are you stuck?

If you want to use the project as a library from your code, then use Maven central and see the code / Javadocs / tests for usage examples.

If you are trying to run the project as standalone, then please download the latest release ZIP and launch the scripts in bin/ directory as described.

**Comment by chahna107** [comment]
@loomchild 
I am trying to run the project as standalone and I copied the scripts to bin/ directory. But when I type **maligna** from command line, it gives me this error - `Error: Could not find or load main class net.loomchild.maligna.ui.console.Maligna`

**Comment by loomchild** [comment]
Please do not copy the scripts - the scripts need to stay where they are after unpacking the archive. The error is normal as the script is not able to find the Java library in lib/. If you want to move them, you'd need to modify the scripts (there's not a specific system-level installation procedure at the moment). 

If you want to use maligna globally on your system, add `/path/to/maligna/bin`, for example `/opt/maligna/bin` to your PATH environment variable.

**Comment by chahna107** [comment]
So in the latest repo that you have, there is no directory called `bin`. The contents of `bin` that you are referring to are under `maligna/maligna-ui/src/main/scripts`. So I added that path to the PATH environment variable, but it still gave me the error I mentioned above.

On the other hand, I then downloaded the older release 2.7.1 which has a `bin` folder. I added this to the path and I am able to run the commands well.

If you could please verify that the current code works and update the readme accordingly, it may be helpful for others when using this latest release.

Thanks!

**Comment by loomchild** [comment]
I can see bin/ directory in https://github.com/loomchild/maligna/releases/download/3.0.0/maligna-3.0.0.zip (latest release), so there's nothing to be updated. 

It's normal than in the`source tree scripts are located in a different place than in the final artifact - I am following Maven repository rules here. You are not supposed to run the source directly, it needs to be built first (this is generally true for any software except for simple scripts).

**Comment by chahna107** [comment]
Got it. Thank you!
