### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by doxa-pgt** [loomchild/maligna#7]
Sorry for such as dumb question, but I can't find how to install on Ubuntu server 20.04, please could you helpme with a instructions for a novice in java?

**Comment by loomchild** [comment]
Hi,

Go the latest release: https://github.com/loomchild/maligna/releases/tag/3.0.0 and download the maligna-*.zip file. Unpack it and run bin/maligna script. You would need to install Java JRE, not sure how it works exactly on Ubuntu, but you could try a tutorial like this one: https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-on-ubuntu-20-04.

Please let me know if it works.

Jarek

**Comment by doxa-pgt** [comment]
Thank you for your help, I confirm that it is working now, and to note that is very important to install the jdk 1.6 as you mention.
