### ISSUE TITLE
Need a maven artifact for maligna-ui.jar

### ISSUE THREAD

**Issue by alaindesilets** [loomchild/maligna#8]
I need to include both maligna and maligna-ui in my pom.xml.

So I put the following in my pom.xml

              <dependency>
		    <groupId>net.loomchild</groupId>
		    <artifactId>maligna-ui</artifactId>
		    <version>3.0.1</version>
		</dependency>
	  
		<dependency>
		    <groupId>com.github.loomchild.maligna</groupId>
		    <artifactId>maligna</artifactId>
		    <version>3.0.1</version>
		</dependency>

When I do a mvn install, it does find the maligna dependency, but not maligna-ui. And indeed, I see that there is an artifact for malignal here:

   https://mvnrepository.com/artifact/net.loomchild/maligna

but I can't find one for maligna-ui. I tried getting the dependency directly from the github repo using jitpack, but it doesn't find it either. I think that's because maligna-ui.jar is not included in the releases for maligna. For example here is the release for 3.0.1:

https://github.com/loomchild/maligna/releases/tag/3.0.1

Would it be possible to provide a maven artifact for maligna-ui? Or at least include that jar in the maligna release so I can include it using jitpack?

Thx.

**Comment by loomchild** [comment]
Yes, the UI part is not shared in Maven Central, since this module is not meant to be used by other Java programs. I think it's a much better idea to chain the commands programmatically, as you mentioned in the other issue.

If you still need to UI part for some reason, you can get it from binary ZIP release (in lib/ directory).

**Comment by alaindesilets** [comment]
> Yes, the UI part is not shared in Maven Central, since this module is not meant to be used by other Java programs. I think it's a much better idea to chain the commands programmatically, as you mentioned in the other issue.

The problem is that the various Commands are defined in maligna-ui, not maligna. So if you want to use maligna from a Java app without having to invoke it in an external process, you need to add maligna-ui to your pom.

If the Commands were moved from maligna-ui module to the maligna module, then I wouldn't need to include maligna-ui in my pom. So maybe the right solution is to do that.
